apiVersion: v1
kind: Service
metadata:
    name: tracking-service
    namespace: acubed
    labels:
      app: tracking-service
spec:
    clusterIP: None
    ports:
    - port: 50551 
      name: tracking-service
    selector:
      app: tracking-service